apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m0s
  path: ./metallb
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
