apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  # - github.com/metallb/metallb/config/frr?ref=v0.13.12
  - github.com/metallb/metallb/config/frr?ref=v0.14.8
  # - raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-frr.yaml
  - ip-address-pool.yaml
  - l2-advertisement.yaml
